// <auto-generated />
using System;
using ClashOfClans.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClashOfClans.API.Migrations
{
    [DbContext(typeof(ClashOfClansContext))]
    [Migration("20250918231854_adicionando_referencias")]
    partial class adicionando_referencias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClashOfClans.API.Model.Clan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_clan");

                    b.ToTable("clan", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Membro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanId")
                        .HasColumnType("int")
                        .HasColumnName("clan_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("situacao");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_membro");

                    b.HasIndex("ClanId")
                        .HasDatabaseName("ix_membro_clan_id");

                    b.ToTable("membro", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Membro", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.Clan", null)
                        .WithMany("Membros")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membro_clans_clan_id");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Clan", b =>
                {
                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
