// <auto-generated />
using System;
using ClashOfClans.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClashOfClans.API.Migrations
{
    [DbContext(typeof(ClashOfClansContext))]
    [Migration("20251030232323_removendo_tag_inutilizada")]
    partial class removendo_tag_inutilizada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClashOfClans.API.Model.Clan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_clan");

                    b.HasIndex("Tag")
                        .IsUnique()
                        .HasDatabaseName("ix_clan_tag");

                    b.ToTable("clan", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.Ataque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AtacanteTag")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("atacante_tag");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("DefensorTag")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("defensor_tag");

                    b.Property<int>("Estrelas")
                        .HasColumnType("int")
                        .HasColumnName("estrelas");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<int?>("MembroEmGuerraId")
                        .HasColumnType("int")
                        .HasColumnName("membro_em_guerra_id");

                    b.Property<int>("MembroId")
                        .HasColumnType("int")
                        .HasColumnName("membro_id");

                    b.HasKey("Id")
                        .HasName("pk_guerra_membro_ataque");

                    b.HasIndex("MembroEmGuerraId")
                        .HasDatabaseName("ix_guerra_membro_ataque_membro_em_guerra_id");

                    b.ToTable("guerra_membro_ataque", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.ClanEmGuerra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<int>("GuerraId")
                        .HasColumnType("int")
                        .HasColumnName("guerra_id");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_clan_em_guerra");

                    b.HasIndex("GuerraId")
                        .IsUnique()
                        .HasDatabaseName("ix_clan_em_guerra_guerra_id");

                    b.ToTable("clan_em_guerra", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.Guerra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("FimGuerra")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fim_guerra");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<DateTime>("InicioGuerra")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("inicio_guerra");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_guerra");

                    b.HasIndex("InicioGuerra", "FimGuerra")
                        .IsUnique()
                        .HasDatabaseName("ix_guerra_inicio_guerra_fim_guerra");

                    b.ToTable("guerra", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.MembroEmGuerra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClanEmGuerraId")
                        .HasColumnType("int")
                        .HasColumnName("clan_em_guerra_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_membro_em_guerra");

                    b.HasIndex("ClanEmGuerraId")
                        .HasDatabaseName("ix_membro_em_guerra_clan_em_guerra_id");

                    b.ToTable("membro_em_guerra", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Membro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanId")
                        .HasColumnType("int")
                        .HasColumnName("clan_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("situacao");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_membro");

                    b.HasIndex("ClanId")
                        .HasDatabaseName("ix_membro_clan_id");

                    b.HasIndex("Tag")
                        .IsUnique()
                        .HasDatabaseName("ix_membro_tag");

                    b.ToTable("membro", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.Ataque", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.Guerras.MembroEmGuerra", null)
                        .WithMany("Ataques")
                        .HasForeignKey("MembroEmGuerraId")
                        .HasConstraintName("fk_guerra_membro_ataque_membro_em_guerra_membro_em_guerra_id");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.ClanEmGuerra", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.Guerras.Guerra", "Guerra")
                        .WithOne("ClanEmGuerra")
                        .HasForeignKey("ClashOfClans.API.Model.Guerras.ClanEmGuerra", "GuerraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clan_em_guerra_guerras_guerra_id");

                    b.Navigation("Guerra");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.MembroEmGuerra", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.Guerras.ClanEmGuerra", null)
                        .WithMany("Membros")
                        .HasForeignKey("ClanEmGuerraId")
                        .HasConstraintName("fk_membro_em_guerra_clan_em_guerra_clan_em_guerra_id");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Membro", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.Clan", null)
                        .WithMany("Membros")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membro_clans_clan_id");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Clan", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.ClanEmGuerra", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.Guerra", b =>
                {
                    b.Navigation("ClanEmGuerra")
                        .IsRequired();
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.MembroEmGuerra", b =>
                {
                    b.Navigation("Ataques");
                });
#pragma warning restore 612, 618
        }
    }
}
