// <auto-generated />
using System;
using ClashOfClans.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClashOfClans.API.Migrations
{
    [DbContext(typeof(ClashOfClansContext))]
    [Migration("20251215172247_RelacionandoTabelasDeGuerras")]
    partial class RelacionandoTabelasDeGuerras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            //MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClashOfClans.API.Model.Clans.Clan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_clan");

                    b.HasIndex("Tag")
                        .IsUnique()
                        .HasDatabaseName("ix_clan_tag");

                    b.ToTable("clan", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Clans.Membro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanId")
                        .HasColumnType("int")
                        .HasColumnName("clan_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataEntrada")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_entrada");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("situacao");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_membro");

                    b.HasIndex("ClanId")
                        .HasDatabaseName("ix_membro_clan_id");

                    b.HasIndex("Tag")
                        .IsUnique()
                        .HasDatabaseName("ix_membro_tag");

                    b.ToTable("membro", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.ClanEmGuerra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<int>("GuerraId")
                        .HasColumnType("int")
                        .HasColumnName("guerra_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_clan_em_guerra");

                    b.HasIndex("GuerraId")
                        .IsUnique()
                        .HasDatabaseName("ix_clan_em_guerra_guerra_id");

                    b.HasIndex("GuerraId", "Tag")
                        .IsUnique()
                        .HasDatabaseName("ix_clan_em_guerra_guerra_id_tag");

                    b.ToTable("clan_em_guerra", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.Guerra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanEmGuerraId")
                        .HasColumnType("int")
                        .HasColumnName("clan_em_guerra_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("FimGuerra")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("fim_guerra");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("GuerraTag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("guerra_tag");

                    b.Property<DateTime>("InicioGuerra")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("inicio_guerra");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.Property<string>("TipoGuerra")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_guerra");

                    b.HasKey("Id")
                        .HasName("pk_guerra");

                    b.ToTable("guerra", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.GuerraMembroAtaque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AtacanteTag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("atacante_tag");

                    b.Property<DateTime>("DataAlteracao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("DefensorTag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("defensor_tag");

                    b.Property<int>("Estrelas")
                        .HasColumnType("int")
                        .HasColumnName("estrelas");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<int>("MembroEmGuerraId")
                        .HasColumnType("int")
                        .HasColumnName("membro_em_guerra_id");

                    b.HasKey("Id")
                        .HasName("pk_guerra_membro_ataque");

                    b.HasIndex("MembroEmGuerraId")
                        .HasDatabaseName("ix_guerra_membro_ataque_membro_em_guerra_id");

                    b.HasIndex("AtacanteTag", "DefensorTag", "MembroEmGuerraId")
                        .IsUnique()
                        .HasDatabaseName("ix_guerra_membro_ataque_atacante_tag_defensor_tag_membro_em_gue");

                    b.ToTable("guerra_membro_ataque", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.MembroEmGuerra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroVilaLevel")
                        .HasColumnType("int")
                        .HasColumnName("centro_vila_level");

                    b.Property<int>("ClanEmGuerraId")
                        .HasColumnType("int")
                        .HasColumnName("clan_em_guerra_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_membro_em_guerra");

                    b.HasIndex("ClanEmGuerraId")
                        .HasDatabaseName("ix_membro_em_guerra_clan_em_guerra_id");

                    b.ToTable("membro_em_guerra", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.LigaDeClans.LigaDeGuerra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clan_tag");

                    b.Property<DateTime>("DataAlteracao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.Property<string>("Temporada")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("temporada");

                    b.HasKey("Id")
                        .HasName("pk_liga_guerra");

                    b.HasIndex("Temporada")
                        .IsUnique()
                        .HasDatabaseName("ix_liga_guerra_temporada");

                    b.ToTable("liga_guerra", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.LigaDeClans.LigaGuerraClan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanLevel")
                        .HasColumnType("int")
                        .HasColumnName("clan_level");

                    b.Property<DateTime>("DataAlteracao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<int?>("LigaDeGuerraId")
                        .HasColumnType("int")
                        .HasColumnName("liga_de_guerra_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_liga_guerra_clan");

                    b.HasIndex("LigaDeGuerraId")
                        .HasDatabaseName("ix_liga_guerra_clan_liga_de_guerra_id");

                    b.ToTable("liga_guerra_clan", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.LigaDeClans.LigaGuerraMembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroVilaLevel")
                        .HasColumnType("int")
                        .HasColumnName("centro_vila_level");

                    b.Property<DateTime>("DataAlteracao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_criacao");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<int?>("LigaGuerraClanId")
                        .HasColumnType("int")
                        .HasColumnName("liga_guerra_clan_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.HasKey("Id")
                        .HasName("pk_liga_guerra_membro");

                    b.HasIndex("LigaGuerraClanId")
                        .HasDatabaseName("ix_liga_guerra_membro_liga_guerra_clan_id");

                    b.ToTable("liga_guerra_membro", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.LigaDeClans.LigaGuerraRodada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clan_tag");

                    b.Property<string>("ClanTagOponente")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clan_tag_oponente");

                    b.Property<DateTime>("DataAlteracao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_criacao");

                    b.Property<int>("Dia")
                        .HasColumnType("int")
                        .HasColumnName("dia");

                    b.Property<DateTime>("FimGuerra")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("fim_guerra");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("GuerraTag")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("guerra_tag");

                    b.Property<DateTime>("InicioGuerra")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("inicio_guerra");

                    b.Property<int?>("LigaDeGuerraId")
                        .HasColumnType("int")
                        .HasColumnName("liga_de_guerra_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_liga_guerra_rodada");

                    b.HasIndex("LigaDeGuerraId")
                        .HasDatabaseName("ix_liga_guerra_rodada_liga_de_guerra_id");

                    b.ToTable("liga_guerra_rodada", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.MembroGuerraResumo", b =>
                {
                    b.Property<string>("MembroTag")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("membro_tag");

                    b.Property<string>("ClanTag")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clan_tag");

                    b.Property<int>("GuerrasParticipadasSeq")
                        .HasColumnType("int")
                        .HasColumnName("guerras_participadas_seq");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("QuantidadeAtaques")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_ataques");

                    b.HasKey("MembroTag", "ClanTag")
                        .HasName("pk_membros_guerras_resumo");

                    b.ToTable("membros_guerras_resumo", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.MembroInativoGuerra", b =>
                {
                    b.Property<string>("MembroTag")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("membro_tag");

                    b.Property<string>("ClanTag")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clan_tag");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_avaliacao");

                    b.Property<DateTime>("DataEntradaMembro")
                        .HasPrecision(0)
                        .HasColumnType("datetime(0)")
                        .HasColumnName("data_entrada_membro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("MembroTag", "ClanTag")
                        .HasName("pk_membro_inativo_guerra");

                    b.ToTable("membro_inativo_guerra", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Clans.Membro", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.Clans.Clan", null)
                        .WithMany("Membros")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membro_clan_clan_id");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.ClanEmGuerra", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.Guerras.Guerra", null)
                        .WithOne("ClanEmGuerra")
                        .HasForeignKey("ClashOfClans.API.Model.Guerras.ClanEmGuerra", "GuerraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clan_em_guerra_guerras_guerra_id");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.GuerraMembroAtaque", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.Guerras.MembroEmGuerra", "MembroEmGuerra")
                        .WithMany("Ataques")
                        .HasForeignKey("MembroEmGuerraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guerra_membro_ataque_membros_em_guerra_membro_em_guerra_id");

                    b.Navigation("MembroEmGuerra");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.MembroEmGuerra", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.Guerras.ClanEmGuerra", "ClanEmGuerra")
                        .WithMany("MembrosEmGuerra")
                        .HasForeignKey("ClanEmGuerraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membro_em_guerra_clan_em_guerra_clan_em_guerra_id");

                    b.Navigation("ClanEmGuerra");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.LigaDeClans.LigaGuerraClan", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.LigaDeClans.LigaDeGuerra", null)
                        .WithMany("Clans")
                        .HasForeignKey("LigaDeGuerraId")
                        .HasConstraintName("fk_liga_guerra_clan_liga_de_guerras_liga_de_guerra_id");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.LigaDeClans.LigaGuerraMembro", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.LigaDeClans.LigaGuerraClan", null)
                        .WithMany("Membros")
                        .HasForeignKey("LigaGuerraClanId")
                        .HasConstraintName("fk_liga_guerra_membro_liga_guerra_clan_liga_guerra_clan_id");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.LigaDeClans.LigaGuerraRodada", b =>
                {
                    b.HasOne("ClashOfClans.API.Model.LigaDeClans.LigaDeGuerra", null)
                        .WithMany("Rodadas")
                        .HasForeignKey("LigaDeGuerraId")
                        .HasConstraintName("fk_liga_guerra_rodada_liga_de_guerras_liga_de_guerra_id");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Clans.Clan", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.ClanEmGuerra", b =>
                {
                    b.Navigation("MembrosEmGuerra");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.Guerra", b =>
                {
                    b.Navigation("ClanEmGuerra")
                        .IsRequired();
                });

            modelBuilder.Entity("ClashOfClans.API.Model.Guerras.MembroEmGuerra", b =>
                {
                    b.Navigation("Ataques");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.LigaDeClans.LigaDeGuerra", b =>
                {
                    b.Navigation("Clans");

                    b.Navigation("Rodadas");
                });

            modelBuilder.Entity("ClashOfClans.API.Model.LigaDeClans.LigaGuerraClan", b =>
                {
                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
