// <auto-generated />
using System;
using ClashOfClans.Integracao.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClashOfClans.Integracao.API.Migrations
{
    [DbContext(typeof(ClashOfClansContext))]
    [Migration("20250513211810_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClashOfClans.Integracao.API.Model.Guerras.BadgeUrls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clan_tag");

                    b.Property<string>("Large")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("large");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("medium");

                    b.Property<string>("OpponentTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("opponent_tag");

                    b.Property<string>("Small")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("small");

                    b.HasKey("Id")
                        .HasName("pk_badge_urls");

                    b.HasIndex("ClanTag")
                        .IsUnique()
                        .HasDatabaseName("ix_badge_urls_clan_tag");

                    b.ToTable("badge_urls", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.Integracao.API.Model.Guerras.Clan", b =>
                {
                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.Property<int>("Attacks")
                        .HasColumnType("int")
                        .HasColumnName("attacks");

                    b.Property<int>("ClanLevel")
                        .HasColumnType("int")
                        .HasColumnName("clan_level");

                    b.Property<double>("DestructionPercentage")
                        .HasColumnType("double")
                        .HasColumnName("destruction_percentage");

                    b.Property<int>("ExpEarned")
                        .HasColumnType("int")
                        .HasColumnName("exp_earned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Stars")
                        .HasColumnType("int")
                        .HasColumnName("stars");

                    b.HasKey("Tag")
                        .HasName("ak_clan_tag");

                    b.ToTable("clan", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.Integracao.API.Model.Guerras.Guerra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttacksPerMember")
                        .HasColumnType("int")
                        .HasColumnName("attacks_per_member");

                    b.Property<string>("BattleModifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("battle_modifier");

                    b.Property<string>("ClanId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("clan_id");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_time");

                    b.Property<bool?>("FoiRemovido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("foi_removido");

                    b.Property<string>("OpponentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("opponent_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("result");

                    b.Property<int>("TeamSize")
                        .HasColumnType("int")
                        .HasColumnName("team_size");

                    b.HasKey("Id")
                        .HasName("pk_guerra");

                    b.HasIndex("ClanId")
                        .HasDatabaseName("ix_guerra_clan_id");

                    b.HasIndex("OpponentId")
                        .HasDatabaseName("ix_guerra_opponent_id");

                    b.ToTable("guerra", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.Integracao.API.Model.Guerras.Opponent", b =>
                {
                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tag");

                    b.Property<int>("ClanLevel")
                        .HasColumnType("int")
                        .HasColumnName("clan_level");

                    b.Property<double>("DestructionPercentage")
                        .HasColumnType("double")
                        .HasColumnName("destruction_percentage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Stars")
                        .HasColumnType("int")
                        .HasColumnName("stars");

                    b.HasKey("Tag")
                        .HasName("ak_opponent_tag");

                    b.ToTable("opponent", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.Integracao.API.Model.Historico", b =>
                {
                    b.Property<string>("NomeRecurso")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_recurso");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_importacao");

                    b.Property<string>("ReferenciaId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("referencia_id");

                    b.HasKey("NomeRecurso")
                        .HasName("pk_historico_integracao");

                    b.ToTable("historico_integracao", (string)null);
                });

            modelBuilder.Entity("ClashOfClans.Integracao.API.Model.Guerras.BadgeUrls", b =>
                {
                    b.HasOne("ClashOfClans.Integracao.API.Model.Guerras.Clan", "Clan")
                        .WithOne("BadgeUrls")
                        .HasForeignKey("ClashOfClans.Integracao.API.Model.Guerras.BadgeUrls", "ClanTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_badge_urls_clan_clan_tag");

                    b.HasOne("ClashOfClans.Integracao.API.Model.Guerras.Opponent", "Opponent")
                        .WithOne("BadgeUrls")
                        .HasForeignKey("ClashOfClans.Integracao.API.Model.Guerras.BadgeUrls", "ClanTag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_badge_urls_opponent_clan_tag");

                    b.Navigation("Clan");

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("ClashOfClans.Integracao.API.Model.Guerras.Guerra", b =>
                {
                    b.HasOne("ClashOfClans.Integracao.API.Model.Guerras.Clan", "Clan")
                        .WithMany()
                        .HasForeignKey("ClanId")
                        .HasConstraintName("fk_guerra_clan_clan_id");

                    b.HasOne("ClashOfClans.Integracao.API.Model.Guerras.Opponent", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guerra_opponent_opponent_id");

                    b.Navigation("Clan");

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("ClashOfClans.Integracao.API.Model.Guerras.Clan", b =>
                {
                    b.Navigation("BadgeUrls")
                        .IsRequired();
                });

            modelBuilder.Entity("ClashOfClans.Integracao.API.Model.Guerras.Opponent", b =>
                {
                    b.Navigation("BadgeUrls")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
