// <auto-generated />
using System;
using ClashOfClans.Integracao.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClashOfClans.Integracao.API.Migrations
{
    [DbContext(typeof(ClashOfClansContext))]
    partial class ClashOfClansContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ClashOfClans.Integracao.API.Model.Historico", b =>
                {
                    b.Property<string>("NomeRecurso")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_recurso");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_importacao");

                    b.Property<string>("ReferenciaId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("referencia_id");

                    b.HasKey("NomeRecurso")
                        .HasName("pk_historico_integracao");

                    b.ToTable("historico_integracao", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
